### ISSUE TITLE
Bob The Fish theme and virtualenvs

### ISSUE THREAD

**Issue by leebrooks0** [bpinto/oh-my-fish#383]
@bobthecow  your theme is amazing!

I have noticed one thing though, when I activate a virtualenv i get (venv) preceding the prompt.

When I turn the prompt off via VIRTUAL_ENV_DISABLE_PROMPT the virtualenv prompt goes away, but immediately afterwards the prompt has the white error sign. Is it possible to disable it?

Here is a screenshot
![fish](https://cloud.githubusercontent.com/assets/2501773/6251611/8596da28-b79d-11e4-88ea-db0652ee4289.png)

Line 3 contains the issue. Is there something I can do about it?

**Comment by bobthecow** [comment]
Thanks :)

That isn't an error, it's just letting you know that the exit status of the last thing you ran was non-zero. A non-zero exit status is _often_ an error — possibly even _usually_ — but it doesn't have to be. You can test it out:

![screen shot 2015-02-18 at 10 29 26 am](https://cloud.githubusercontent.com/assets/53660/6253804/0d6c1d9a-b759-11e4-87eb-cad5d86468fe.png)

As you can see in my example, in fish `if` blocks have an exit status, because that's how you do else:

```fish
if false
  echo "this will never happen"
end; or echo "yeah, this one works"
```

Because `activate.fish` ends on an `if` block, the result of running it will be "successful" or not depending on the tested value. [As we can see here](https://hg.python.org/cpython/file/78145e6ffb40/Lib/venv/scripts/posix/activate.fish#l46) that test is `is the variable $VIRTUAL_ENV_DISABLE_PROMPT empty?`

So the short answer is ask Python to up their fish game and return a proper value from their script. The easy answer is to just ignore it, or to edit the script yourself and add `true` to the end of the file :)

**Comment by leebrooks0** [comment]
Thanks, I am leaning towards options 2 and 3 right now...

**Comment by bobthecow** [comment]
:)
